/bin/sh: discord: command not found
/bin/sh: blueman: command not found
polybar|warn:  No monitor specified, using "VGA-1"

(volnoti:371): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
polybar|error: module/mpd: Connection refused

(volnoti:371): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(nitrogen:369): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(nitrogen:369): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(nitrogen:369): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(nitrogen:369): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
polybar|warn:  pulseaudio: using default sink alsa_output.pci-0000_00_05.0.analog-stereo
polybar|error: module/mpd: Connection refused
Failed to connect to session manager: Failed to connect to the session manager: SESSION_MANAGER environment variable not defined
polybar|error: module/mpd: Connection refused
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.bluez': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/blueman-applet", line 121, in <module>
    BluemanApplet()
  File "/usr/bin/blueman-applet", line 63, in __init__
    self.Plugins.Load()
  File "/usr/lib/python3.6/site-packages/blueman/main/PluginManager.py", line 90, in Load
    __import__(self.module_path.__name__ + ".%s" % plugin, None, None, [])
  File "/usr/lib/python3.6/site-packages/blueman/plugins/applet/DBusService.py", line 12, in <module>
    from blueman.main.applet.BluezAgent import AdapterAgent
  File "/usr/lib/python3.6/site-packages/blueman/main/applet/BluezAgent.py", line 23, in <module>
    from blueman.bluez.Agent import Agent, AgentMethod
  File "/usr/lib/python3.6/site-packages/blueman/bluez/Agent.py", line 48, in <module>
    class Agent(dbus.service.Object):
  File "/usr/lib/python3.6/site-packages/blueman/bluez/Agent.py", line 56, in Agent
    @AgentMethod
  File "/usr/lib/python3.6/site-packages/blueman/bluez/Agent.py", line 38, in AgentMethod
    if BlueZInterface.get_interface_version()[0] < 5:
  File "/usr/lib/python3.6/site-packages/blueman/bluez/BlueZInterface.py", line 16, in get_interface_version
    obj = dbus.SystemBus().get_object('org.bluez', '/')
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.systemd1.NoSuchUnit: Unit dbus-org.bluez.service not found.
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
polybar|error: module/mpd: Connection refused
